### ISSUE TITLE
Synchronization of data and timestamp

### ISSUE THREAD

**Issue by ayanray089** [phil65/ibadatfile#2]
Hi @phil65 ,

Nice code and really helpful. I have a question.
How are you ensuring that data points and timestamp are in sync.
In the code, we extracting the data points separately from timestamp and then merging the timestamp back to the dataframe consisting of data.
In case the data points are lesser than number of timestamps or in other words if there are missing data points how can you ensure that the data points are still in sync with the timestamp.
Seeking your advice on this.

Thanks!

**Comment by phil65** [comment]
Sorry, missed to answer this. Can you provide an example file?
