### ISSUE TITLE
I have a question how can I get IbaFiles.dll?

### ISSUE THREAD

**Issue by bhyoon1110** [phil65/ibadatfile#3]
I installed and run as your instruction, but error raised that no dll files.

**Comment by Leodal24** [comment]
Hi!

Thanks for your project sharing.
Just I designed to get data from iba thru Python, and found your project.
Same as above, no dll files & want to know how to use the project for getting data from iba.
Thanks again for sharing & waiting for your notes.

SIncerely.

**Comment by MoPrince** [comment]
Hi @bhyoon1110 & @Leodal24 

Please ensure you are running python 32-bit. A 32-bit COM object can only be accessed by a 32-bit application, which ibaAnalyzer is 32-bit. If your Python installation is 64-bit, it won't be able to interact with a 32-bit COM object, leading to errors like the one you're encountering.

**Comment by MoPrince** [comment]
Please close this issue.
