### ISSUE TITLE
client.dynamic.Dispatch("IbaFilesLite.IbaFile")` error

### ISSUE THREAD

**Issue by ShiyuCHEN2003** [phil65/ibadatfile#4]
May I ask if this restriction windows version requirements, I use win11 version after registering dll will still report an error.
`Traceback (most recent call last):
  File "C:\Users\ShiYu Chen\Downloads\ibadatfile-master\ibadatfile\ibadatfile.py", line 108, in __init__
    self.reader = client.dynamic.Dispatch("IbaFilesLite.IbaFile")`

**Comment by fredO13** [comment]
also got an error on that same line. 
I made sure the COM library has been registered with windows first using regsvr32.

**Comment by MoPrince** [comment]
@ShiyuCHEN2003 & @fredO13 

Please ensure you are running python 32-bit. A 32-bit COM object can only be accessed by a 32-bit application, which ibaAnalyzer is 32-bit. If your Python installation is 64-bit, it won't be able to interact with a 32-bit COM object, leading to errors like the one you're encountering.


Please close this issue.
